#!/bin/bash

PROPOSE_POINTS=${PROPOSE_POINTS:-9} # 25
MAX_ITERATIONS=${MAX_ITERATIONS:-3}
MAX_BUDGET=${MAX_BUDGET:-180}
DESIGN_SIZE=${DESIGN_SIZE:-9} # 15
PARAM_SET_FILE=${PARAM_SET_FILE:-$WORKFLOW_SETTINGS_FILE} # $EMEWS_PROJECT_ROOT/data/nt3_nightly.R
